--- 
driver: 
  customize: 
    memory: 1024
  name: vagrant
  network: 
    - 
      - forwarded_port
      - 
        guest: 8980
        host: 8980
provisioner:
  name: chef_solo
platforms: 
  - name: centos-6.5
    attributes: 
      postgresql: 
        client: 
          packages: 
            - postgresql93
            - postgresql93-contrib
            - postgresql93-devel
        config: 
          autovacuum: "on"
          checkpoint_timeout: 15min
          data_directory: /var/lib/pgsql/9.3/data
          shared_preload_libraries: pg_stat_statements
          track_activities: "on"
          track_counts: "on"
          vacuum_cost_delay: 50
        config_pgtune: 
          max_connections: 160
        contrib: 
          extensions: 
            - pageinspect
            - pg_buffercache
            - pg_freespacemap
            - pgrowlocks
            - pg_stat_statements
            - pgstattuple
        dir: /var/lib/pgsql/9.3/data
        enable_pgdg_yum: true
        password: 
          postgres: md5c23797e9a303da48b792b4339c426700
        pg_hba: 
          - 
            addr: ""
            db: all
            method: trust
            type: local
            user: all
          - 
            addr: 127.0.0.1/32
            db: all
            method: trust
            type: host
            user: all
          - 
            addr: "::1/128"
            db: all
            method: trust
            type: host
            user: all
        server: 
          packages: 
            - postgresql93-server
          service_name: postgresql-9.3
        version: "9.3"
suites: 
  - name: default
    run_list: 
      - "recipe[postgresql::client]"
      - "recipe[postgresql::server]"
      - "recipe[postgresql::contrib]"
      - "recipe[postgresql::config_initdb]"
      - "recipe[postgresql::config_pgtune]"
      - "recipe[opennms::default]"
    attributes: 
      opennms: 
        conf: 
          start_timeout: 20
        plugin: 
          nsclient: true
          xml: true
        stable: false
  - name: all
    run_list:
      - "recipe[postgresql::client]"
      - "recipe[postgresql::server]"
      - "recipe[postgresql::contrib]"
      - "recipe[postgresql::config_initdb]"
      - "recipe[postgresql::config_pgtune]"
      - "recipe[opennms::notemplates]"
      - "recipe[opennms::webopts]"
      - "recipe[opennms::resource_type]"
      - "recipe[opennms::snmp_collection]"
      - "recipe[opennms::xml_collection]"
      - "recipe[opennms::wmi_collection]"
      - "recipe[opennms::jdbc_collection]"
      - "recipe[opennms::collection_package]"
      - "recipe[opennms::snmp_collection_service]"
      - "recipe[opennms::xml_collection_service]"
      - "recipe[opennms::wmi_collection_service]"
      - "recipe[opennms::jdbc_collection_service]"
      - "recipe[opennms::snmp_collection_group]"
      - "recipe[opennms::jdbc_query]"
      - "recipe[opennms::wmi_wpm]"
      - "recipe[opennms::xml_source]"
      - "recipe[opennms::xml_group]"
      - "recipe[opennms::eventconf]"
      - "recipe[opennms::event]"
      - "recipe[opennms::poller]"
      - "recipe[opennms::disco_specific]"
      - "recipe[opennms::disco_range]"
      - "recipe[opennms::disco_url]"
      - "recipe[opennms::foreign_source]"
      - "recipe[opennms::service_detector]"
      - "recipe[opennms::policy]"
      - "recipe[opennms::import]"
      - "recipe[opennms::import_node]"
      - "recipe[opennms::import_node_interface]"
      - "recipe[opennms::import_node_interface_service]"
      - "recipe[opennms::snmp_config_definition]"
      - "recipe[opennms::update_snmp_config_definition]"
      - "recipe[opennms::wmi_config_definition]"
      - "recipe[opennms::update_wmi_config_definition]"
      - "recipe[opennms::destination_path]"
      - "recipe[opennms::notification_command]"
      - "recipe[opennms::notifd_autoack]"
      - "recipe[opennms::notification]"
      - "recipe[opennms::user]"
      - "recipe[opennms::group]"
      - "recipe[opennms::role]"
      - "recipe[opennms::statsd]"
      - "recipe[opennms::collection_graph_file]"
      - "recipe[opennms::collection_graph]"
      - "recipe[opennms::response_graph]"
      - "recipe[opennms::threshold]"
      - "recipe[opennms::system_def]"
      - "recipe[opennms::avail_category]"
    attributes: 
      opennms: 
        conf: 
          start_timeout: 20
        plugin: 
          nsclient: true
          xml: true
        stable: false
  - name: jms_nb
    run_list:
      - "recipe[postgresql::client]"
      - "recipe[postgresql::server]"
      - "recipe[postgresql::contrib]"
      - "recipe[postgresql::config_initdb]"
      - "recipe[postgresql::config_pgtune]"
      - "recipe[opennms::default]"
      - "recipe[activemq::default]"
      - "recipe[unjava::unjava]"
    attributes: 
      opennms: 
        conf: 
          start_timeout: 20
        jms_nbi:
          enabled: true
        plugin: 
          nsclient: true
          xml: true
        properties: 
          jms_nbi:
            broker_url: "tcp://localhost:61616"
        stable: false
    driver:
      network:
        - ["forwarded_port", {guest: 8980, host: 8980}]
        - ["forwarded_port", {guest: 8161, host: 8161}]
